# Generated by Django 4.1.7 on 2023-03-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0007_alter_cars_condition_alter_cars_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
